### ISSUE TITLE
[QUESTION] single background task

### ISSUE THREAD

**Issue by rspadim** [tiangolo/fastapi#1637]
How could I implement a background task, that only execute once when there's many others tasks like it, for example:

```
# adding task:
task_parameters = 1
background_tasks.add_task(task_function, task_parameters)
```

if the task_function + task_parameters already exists in background_tasks, could i avoid this add_task function?

**Comment by zihaooo** [comment]
You can just go through the background_tasks before add new task to check if the same task exist. Since all tasks in background_tasks are BackgroundTask object https://github.com/encode/starlette/blob/master/starlette/background.py , you can get the function (then the name of the function) and the args of the function.

**Comment by zihaooo** [comment]
You can just traverse the background_tasks before add new task to check if the same task exist. Since all tasks in background_tasks are BackgroundTask object https://github.com/encode/starlette/blob/master/starlette/background.py , you can get the function (then the name of the function) and the args of the function.

**Comment by tiangolo** [comment]
It seems like you would benefit from a more robust task manager, like https://arq-docs.helpmanual.io/ and an external DB or some type of storage to save temporary state, like Redis.

The internal lightweight background tasks are mainly for simple things, like sending email notifications.

If you still want to do it with the internal background tasks, it seems you would still need an external data storage system to coordinate the internal tasks.
