### ISSUE TITLE
SQLAlchemy autoflush doesn't work

### ISSUE THREAD

**Issue by orientalperil** [tiangolo/fastapi#1776]
I'm using FastAPI with SQLAlchemy.  I have a middleware that adds a database session to `request.state` as described in https://fastapi.tiangolo.com/tutorial/sql-databases/#alternative-db-session-with-middleware.  I tried creating the session with `autoflush=True` but found that it has race condition issues where sometimes the flush would happen as I expected and other times it would happen too late.  This can cause a record to not be inserted into the database when I assumed it would be.

What is causing autoflush to fail to work?

**Comment by tiangolo** [comment]
It's very difficult to know without an example replicating the issue. It could be background tasks that try to use the session, those don't work with the middleware technique, because the middleware closes the session before returning the response.

The recommended approach to handle DB sessions is using dependencies with yield. I would suggest you try that.
