### ISSUE TITLE
[FEATURE] Allow more flexible validation of Path parameters

### ISSUE THREAD

**Issue by sscherfke** [tiangolo/fastapi#472]
**Is your feature request related to a problem? Please describe.**
Path parameters can currently only be validated using a regular expression, which may not always be sufficient.

**Describe the solution you'd like**
It would be nice if I could provide a validator function for the `Path` instance that can perform additional checks (and transformation) or raise an error:

```python
def validate_channel(value):
    path = PREFIX / value
    if not path.is_dir():
        raise ValidationError(f"Channel '{value}' does not exist")  # I know, this could actually be a 404 ;-)
    return path

@app.post("/upload/{channel}")
async def conda_upload(channel: str = Path(validator=validate_channel), ...):
    assert channel.is_dir()
    ...
```

**Describe alternatives you've considered**
Validate inside the function and manually raise an error, see #471 .

**Comment by sscherfke** [comment]
Yes, this would be possible.  I‘ve opened #471 for this.

The use case for both issues is, that it is currently hard to perform additonal validation and return an error that is formatted like the ones returned by the built-in validation.

If #471 will be implemented, this issue can be closed. :)

**Comment by tiangolo** [comment]
Thanks for your help @wshayes !

@sscherfke a simpler way to achieve this would be with a dependency. The dependency could require the path parameter and error out if your custom validation fails. And then your path operations could use that dependency instead of doing all the validation in the main code.

Another option that could be closer to what your want to achieve is a custom Pydantic data type that inherits from a `str`:

https://pydantic-docs.helpmanual.io/#custom-data-types

That's probably what you're looking for.

**Comment by kevlarr** [comment]
> Why not do the validation in the endpoint or a service call? Why does the validator need to be done in the request parameters?

@wshayes Nested routes. If a lot of routes are nested under a resource that requires manually parsing, then it opens up a lot of room for something to be missed.
