### ISSUE TITLE
[QUESTION] More than 20 concurrent tasks are queued

### ISSUE THREAD

**Issue by icebolla** [tiangolo/fastapi#676]
Hi,

I'm using BackgroundTasks following the manual and my process is working properly but I found a limitation. When I execute the background task many times it's like there were a tasks queue and it stops starting processes after 20 running tasks and just when any task ends the other starts (just letting running 20 in parallel).

I've been looking for information with key words starlette, backgroundtasks, asyncio... with no luck. I just found this [page](https://community.yellowfinbi.com/knowledge-base/article/how-to-configure-the-maximum-number-of-background-tasks-to-run-concurrently) but I think it's just for a specific software. 

Could someone give me any clue?

Thanks.

**Comment by dmontagu** [comment]
Are you running on a four core processor? If you give it `def` tasks (instead of `async def`) they will run in a threadpool executor. The default threadpool executor gets five threads per core, so you’ll have at most twenty tasks running at a time. (And that pool is also shared with your server!)

If you have long running background tasks, you may want to refactor them to be async def, or to run somewhere else using something like celery or arq.

**Comment by icebolla** [comment]
Yes, I'm using a four core processor. Now I understand. I'll find out how to change the default executor and if it's not working I'll learn how to use celery and arq. I'll reply with progress made.

**Comment by tiangolo** [comment]
Yep. All what @dmontagu said :point_up: point by point, I couldn't explain it better :smile:
