### ISSUE TITLE
[FEATURE] Support repeated key=value in form data

### ISSUE THREAD

**Issue by StephenCarboni** [tiangolo/fastapi#842]
### Is your feature request related to a problem

Yes.

Given some URL encoded data like this...

```
choices=parrot&choices=spider
```

...only the last key=value wins.

This does not work like I expected:
```python
choices: list = Form(...)
```

You can only validate against the last value.

### The solution you would like

Perhaps FastAPI should collect repeated keys in the 2-tuple list that `request.form()` gives and assign those values as a list to the same key before validation happens.

**Comment by shifr** [comment]
Hey @StephenCarboni, parameters in the URL are part of a querystring and you can get and validate them as described here: https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#query-parameter-list-multiple-values
As far as I understand, `Form()` is using only for request body

**Comment by shifr** [comment]
Oh, sorry, looks like I misread you message.

**Comment by shifr** [comment]
Anyway, I think this issue better be created in the starlette repo, because the `request` is an object from starlette.

**Comment by dmontagu** [comment]
I am a little surprised that `choices=parrot&choices=spider` doesn't work; if I recall correctly it definitely works for query parameters, and is how you would send a list of values.

The logic for form data parsing is in the `starlette.requests.Request.form` method, and delegates to [`python-multipart`](https://github.com/andrew-d/python-multipart), so you can look for the specific logic there.

**Comment by tfishr** [comment]
I just spent three days working on an issue related to this. I'm trying to do something like:

```python
app.post("/post-form-here")
def process_form(form_data: Dict[str, str] = Form(...)):
    pass
```

The fact that this doesn't work is not clear from the documentation. It looks like you can combine [Form Data](https://fastapi.tiangolo.com/tutorial/request-forms/) with [Bodies of Arbitrary `dict`s](https://fastapi.tiangolo.com/tutorial/body-nested-models/#bodies-of-arbitrary-dicts).

I think it should explicitly state you can't combine these concepts, because people are going to waste hundreds of hours trying to do the impossible. If you are using `Form()` you have to explicitly define each form field one by one. In my case there are 27 of them. This is going to be the longest function definition I've ever written in production, but I'd rather do that than waste a whole weekend beating my head against a wall.

**Comment by nsidnev** [comment]
@dmontagu 
Hi! I found some strange behavior regarding this issue. `FastAPI` can correctly validate the list from the form if the parameter is declared as `typing.List[str]`. But if I declare it with `list` annotation, then I get a validation error that the passed data is not a list. I don’t think this is a `Starlette` issue, because calling the `request.form()` returns the correct results that can be obtained by calling `FormData.getlist("choices")`.

Here is my example application:
```python3
from typing import List

from fastapi import FastAPI, Form
from starlette.requests import Request

app = FastAPI()


@app.post("/typing-list-annotation")
async def typing_list(choices: List[str] = Form(...)) -> dict:
    return {"choices": choices}


@app.post("/simple-list-annotation")
async def simple_list(choices: list = Form(...)) -> dict:
    return {"choices": choices}


@app.post("/request-passing")
async def request_passing(request: Request) -> dict:
    return {"choices": (await request.form()).getlist("choices")}

```

And example of wrong request:
```bash
$ http -f -v POST :8000/simple-list-annotation choices=a choices=2               
POST /simple-list-annotation HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 19
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: localhost:8000
User-Agent: HTTPie/1.0.3

choices=a&choices=2

HTTP/1.1 422 Unprocessable Entity
content-length: 98
content-type: application/json
date: Tue, 14 Jan 2020 02:31:04 GMT
server: uvicorn

{
    "detail": [
        {
            "loc": [
                "body",
                "choices"
            ],
            "msg": "value is not a valid list",
            "type": "type_error.list"
        }
    ]
}
```

The problem is in [this](https://github.com/tiangolo/fastapi/blob/3eca945bd17600a0be6eae1d8fd93ba8f9805006/fastapi/dependencies/utils.py#L632) line. When a form parameter is converted to a `pydantic` field, it is identified as `pydantic.fields.SHAPE_SINGLETON` instead of `pydantic.fields.SHAPE_LIST` when the `list` annotation is used. After that, when validating the form, `FastAPI` is unable to understand that this is a list and tries to get a sinlge value which causes `ValidationError`. I've pushed a PR that should fix this.

**Comment by dmontagu** [comment]
Yep, this seems to be an awkwardness with pydantic; thanks for submitting the fix!

**Comment by tiangolo** [comment]
Thanks @StephenCarboni for the report :mag: :male_detective: 

Thanks @nsidnev for the fix! :tada: :rocket: 

And thanks everyone here for the discussion.

This is available in the latest release.

**Comment by jhaoheng** [comment]
Hi, 

```
@app.post("/root")
async def root(ids: List[str] = Form(...)):
    return ids
```

- fastapi version : 0.61.0

I use CURL to run the api, it works ...
But, if I use `/docs` (the default UI) to run this api, return `["obj_1, obj_2"]`
I think it should be `["obj_1", "obj_2"]`

**Comment by HitLuca** [comment]
I think we still have an issue with `Form` and `List`. When passing a list of elements as a Form field, it doesn't get parsed correctly:

```python
@app.put("/test1")
def test1(values: List[str] = Form(...)) -> None:
    return values


@app.put("/test2")
def test2(values: List[str] = Query(...)) -> None:
    return values
```

test1 example

```bash
curl -X 'PUT' \
  'http://localhost:5050/test1' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'values=string,string'
```

```json
[
  "string,string"
]
```

test2 example

```bash
curl -X 'PUT' \
  'http://localhost:5050/test2?values=string&values=string' \
  -H 'accept: application/json'
```

```json
[
  "string",
  "string"
]
```

we can see how `Query` correctly parses the list, whereas `Form` doesn't. Changing `List[str]` to `list` doesn't fix the problem. Accepting list of numbers with `List[int]` for example returns an error as shown below, indicating that `typing.List` isn't handled as expected

```python
@app.put("/test3")
def test2(values: List[int] = Form(...)) -> None:
    print(type(values), values)
    return values
```

test3 example

```bash
curl -X 'PUT' \
  'http://localhost:5050/test3' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'values=1,2'
```

```json
{
  "detail": [
    {
      "loc": [
        "body",
        "values",
        0
      ],
      "msg": "value is not a valid integer",
      "type": "type_error.integer"
    }
  ]
}
```

**Comment by HitLuca** [comment]
Any feedback on the new findings?
