### ISSUE TITLE
[BUG] FastAPI does not set additionalProperties correctly when dealing with Dicts.

### ISSUE THREAD

**Issue by Sean1708** [tiangolo/fastapi#87]
**Describe the bug**
When creating the schema for a `Dict` FastAPI sets `"additionalProperties": true` instead of setting it to the schema of the values. This does not appear to be an issue with pydantic.

**To Reproduce**
A minimal working example is:

```python
from typing import Dict

from fastapi import FastAPI
from pydantic import BaseModel


app = FastAPI()


class Items(BaseModel):
	items: Dict[str, int]


@app.post("/foo")
def foo(items: Items):
	return items.items
```

Put this in a file called `test.py` and run it with `uvicorn test:app`. The JSON returned from the `openapi.json` endpoint is:

```json
{"openapi":"3.0.2","info":{"title":"Fast API","version":"0.1.0"},"paths":{"/foo":{"post":{"responses":{"200":{"description":"Successful Response","content":{"application/json":{"schema":{}}}},"422":{"description":"Validation Error","content":{"application/json":{"schema":{"$ref":"#/components/schemas/HTTPValidationError"}}}}},"summary":"Foo Post","operationId":"foo_foo_post","requestBody":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/Items"}}},"required":true}}}},"components":{"schemas":{"Items":{"title":"Items","required":["items"],"type":"object","properties":{"items":{"title":"Items","type":"object","additionalProperties":true}}},"ValidationError":{"title":"ValidationError","required":["loc","msg","type"],"type":"object","properties":{"loc":{"title":"Location","type":"array","items":{"type":"string"}},"msg":{"title":"Message","type":"string"},"type":{"title":"Error Type","type":"string"}}},"HTTPValidationError":{"title":"HTTPValidationError","type":"object","properties":{"detail":{"title":"Detail","type":"array","items":{"$ref":"#/components/schemas/ValidationError"}}}}}}}
```

In particular the schema for `Items` is:

```json
{"title":"Items","required":["items"],"type":"object","properties":{"items":{"title":"Items","type":"object","additionalProperties":true}}}
```

**Expected behavior**
The `additionalProperties` should be `{'type': 'integer'}` as it is when using pydantic directly:

```
Python 3.7.2 (default, Dec 24 2018, 03:41:55) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import test
WARNING:root:email-validator not installed, email fields will be treated as str.
To install, run: pip install email-validator
>>> test.Items.schema()
{'title': 'Items', 'type': 'object', 'properties': {'items': {'title': 'Items', 'type': 'object', 'additionalProperties': {'type': 'integer'}}}, 'required': ['items']}
>>>
```

**Environment:**
 - OS: Linux
 - FastAPI Version 0.8.0
 - Python Version 3.7.2

```
$ pip list
Package    Version
---------- -------
Click      7.0    
fastapi    0.8.0  
h11        0.8.1  
httptools  0.0.13 
pip        18.1   
pydantic   0.18.2 
setuptools 40.6.2 
starlette  0.11.1 
uvicorn    0.6.1  
uvloop     0.12.1 
websockets 7.0
```

**Comment by euri10** [comment]
On that [line](https://github.com/tiangolo/fastapi/blob/60599bad99dc4e2278c8fcf20c85c4afb4b0ca54/fastapi/openapi/utils.py#L249) the output seems correct, so the `OpenAPI(**output)` may be the culprit.

Digging more into the model imbrication, it seems to boil down to 
```
SchemaBase(**{'additionalProperties': {'type': 'integer'}, 'title': 'Items', 'type': 'object'}).dict()
```
that returns in openapi [models](https://github.com/tiangolo/fastapi/blob/60599bad99dc4e2278c8fcf20c85c4afb4b0ca54/fastapi/openapi/models.py#L102) that returns ([....] to shorten the dict)
```
{'ref': None,
 'title': 'Items',
[....]
 'type': 'object',
[....]
 'additionalProperties': True,
[....]
}
```
Not sure how `additionalProperties: Optional[Union[bool, Any]] = None` might be modified if that's effectively here that lies the issue though, but interested in hearing how it's solved ;0)

**Comment by euri10** [comment]
mouarf, nasty intuition, the `items` attribute is likely the culprit in fact, replace by
```
class Items(BaseModel):
    fooff: Dict[str, int]
```
and you got openapi_schema to:
```
{'openapi': '3.0.2',
 'info': {'title': 'Fast API', 'version': '0.1.0'},
 'paths': {'/foo': {'post': {'responses': {'200': {'description': 'Successful Response',
      'content': {'application/json': {'schema': {}}}},
     '422': {'description': 'Validation Error',
      'content': {'application/json': {'schema': {'$ref': '#/components/schemas/HTTPValidationError'}}}}},
    'summary': 'Foo Post',
    'operationId': 'foo_foo_post',
    'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/Items'}}},
     'required': True}}}},
 'components': {'schemas': {'Items': {'title': 'Items',
    'required': ['fooff'],
    'type': 'object',
    'properties': {'fooff': {'title': 'Fooff',
      'type': 'object',
      'additionalProperties': {'type': 'integer'}}}},
   'ValidationError': {'title': 'ValidationError',
    'required': ['loc', 'msg', 'type'],
    'type': 'object',
    'properties': {'loc': {'title': 'Location',
      'type': 'array',
      'items': {'type': 'string'}},
     'msg': {'title': 'Message', 'type': 'string'},
     'type': {'title': 'Error Type', 'type': 'string'}}},
   'HTTPValidationError': {'title': 'HTTPValidationError',
    'type': 'object',
    'properties': {'detail': {'title': 'Detail',
      'type': 'array',
      'items': {'$ref': '#/components/schemas/ValidationError'}}}}}}}
```

**Comment by Sean1708** [comment]
Thanks for figuring this out so quickly, @euri10 !

**Comment by euri10** [comment]
honestly I'm not sure at all if that is the right way to fix it, I've
barely read anything on openapi specifications

**Comment by tiangolo** [comment]
Thanks for the report @Sean1708 .

Great detective job finding where is the issue originated @euri10 :mag: 

We discovered a very subtle bug! :bug: :gun: 

---

In fact, just switching the order solves the problem:

```Python
additionalProperties: Optional[Union[Any, bool]] = None
```

instead of:

```Python
additionalProperties: Optional[Union[Any, bool]] = None
```

---

Here's the situation/explanation:

All the OpenAPI spec is defined as Pydantic models inside of FastAPI. When the OpenAPI schema is received, it is passed to those models that then validate/serialize it.

There's actually a Pydantic model defining what can be in a JSON Schema, kind of JSON-Schema-ception.

For that specific attribute/field, when receiving the `dict` of the sub-schema: `{'type': 'integer'}`, Pydantic checks, validates, and serializes it to a valid data type. Because the first type in the `Union` was a `bool`, it converted that `dict` to its boolean value (`True`).

The attribute had `Any` instead of a proper definition because the proper definition is itself, so, it's a circular reference. But there's no way to define that in Pydantic/Python 3.6+ (I understand it's possible in Pydantic/Python 3.7 with `ForwardRef`). So, this situation only happens in attributes that have a JSON Schema themselves.

Now, using `Dict[str, Any]` (as @euri10 suggested) is a bit more precise than just `Any`, so I'll use that.

I'm also checking the rest of the models for similar issues or type definition specificity.

The PR is here https://github.com/tiangolo/fastapi/pull/121

I also added your test case exactly, to prevent future regressions.

Let's wait for Travis (that seems to be slow now), and I'll merge it and release.

**Comment by tiangolo** [comment]
It should be fixed now, released in version `0.10.2`. :tada: :rocket:

**Comment by Sean1708** [comment]
Cheers @tiangolo! I can confirm that this now works for me!

**Comment by tiangolo** [comment]
Great! Thanks for reporting back and closing it.
